# Generated by Django 6.0.4 on 2026-04-18 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('age', models.PositiveBigIntegerField()),
                ('nationality', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('height', models.FloatField(blank=True, help_text='Height in centimeters')),
                ('weight', models.FloatField(blank=True, help_text='Weight in kilograms')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('rugby', 'Rugby'), ('cricket', 'Cricket'), ('tennis', 'Tennis'), ('athletics', 'Athletics')], max_length=50)),
                ('position', models.CharField(choices=[('forward', 'Forward'), ('midfielder', 'Midfielder'), ('defender', 'Defender'), ('goalkeeper', 'Goalkeeper')], max_length=50)),
                ('school_team', models.CharField(blank=True, max_length=255)),
                ('club', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AthleteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='athlete_media/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='athletes.athlete')),
            ],
        ),
    ]
