# Generated by Django 6.0.4 on 2026-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='user',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='location',
            field=models.CharField(choices=[('gauteng', 'Gauteng'), ('western cape', 'Western Cape'), ('kwazulu-natal', 'KwaZulu-Natal'), ('free state', 'Free State'), ('eastern cape', 'Eastern Cape'), ('northern cape', 'Northern Cape'), ('mpumalanga', 'Mpumalanga'), ('limpopo', 'Limpopo'), ('north west', 'North West')], max_length=255),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kilograms'),
        ),
    ]
