# Generated by Django 6.0.4 on 2026-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_remove_athlete_user_alter_athlete_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='athlete_media/'),
        ),
        migrations.DeleteModel(
            name='AthleteMedia',
        ),
    ]
