# Generated by Django 6.0.4 on 2026-04-18 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athlete_file_delete_athletemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='age',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='file',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='id_number',
        ),
        migrations.AddField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='location',
            field=models.CharField(choices=[('gauteng', 'Gauteng'), ('western_cape', 'Western Cape'), ('kwazulu_natal', 'KwaZulu-Natal'), ('free_state', 'Free State'), ('eastern_cape', 'Eastern Cape'), ('northern_cape', 'Northern Cape'), ('mpumalanga', 'Mpumalanga'), ('limpopo', 'Limpopo'), ('north_west', 'North West')], max_length=50),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sport',
            field=models.CharField(default='football', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='kg', null=True),
        ),
        migrations.CreateModel(
            name='AthleteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='athlete_media/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='athletes.athlete')),
            ],
        ),
    ]
