# Generated by Django 6.0.4 on 2026-04-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('scouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('johannesburg', 'Johannesburg'), ('cape town', 'Cape Town'), ('durban', 'Durban'), ('pretoria', 'Pretoria'), ('port elizabeth', 'Port Elizabeth'), ('bloemfontein', 'Bloemfontein'), ('east london', 'East London'), ('kimberley', 'Kimberley'), ('nelspruit', 'Nelspruit')], max_length=50)),
                ('trial_date', models.DateField()),
                ('trial_time', models.TimeField()),
                ('trial_duration', models.DurationField()),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts.scoutprofile')),
            ],
        ),
    ]
