# Generated by Django 6.0.4 on 2026-04-18 20:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_remove_invite_trial_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invite',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invite',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invite',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
