# Generated by Django 6.0.4 on 2026-04-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_alter_invite_end_date_alter_invite_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='status',
        ),
    ]
